### PR TITLE
FEATURE: Add fetching watch providers to movie and tv series services

### PR DESCRIPTION
**Pull request by Tuikku**

### CODE REVIEW

**Comment by adamayoung** [comment]
Hey @Tuikku. Thanks for your PR. Did you see there is already a WatchProviders service that does this?

https://github.com/adamayoung/TMDb/blob/main/Sources/TMDb/WatchProviders/WatchProviderService.swift

**Comment by Tuikku** [comment]
Does this fetch the actual providers for individual series or movie?

**Comment by adamayoung** [comment]
Ahhh, i understand now. Thanks for this.

Would appreciate you adding some unit tests around the changes you've made 🙏🏻

**Comment by Tuikku** [comment]
Yeah, I'll add some tests to this pr.

**Comment by Tuikku** [comment]
Added some unit tests, let me know what you think. Didn't add integration tests since watch providers for tv series or movie could change.

**Review by adamayoung — APPROVED** [review]

**Pull request merged**
